CREATE TABLE postventa_intereses_catalogo (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  icono VARCHAR(16) NULL,
  nombre VARCHAR(150) NOT NULL,
  descripcion VARCHAR(300) NULL,
  etiqueta VARCHAR(100) NULL,
  orden INT NOT NULL DEFAULT 0,
  activo TINYINT(1) NOT NULL DEFAULT 1,
  created_by VARCHAR(150) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_activo_orden (activo, orden)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
